baseURL = 'https://shunta-furukawa.info/'
languageCode = 'ja-JP'
title = 'SHUNTA FURUKAWA INFO'

[[menu.main]]
  identifier = "home"
  name = "HOME"
  url = "/#top"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "ABOUT"
  url = "/#about"
  weight = 20

[[menu.main]]
  identifier = "skills"
  name = "SKILLS"
  url = "/#skills"
  weight = 30

[[menu.main]]
  identifier = "story"
  name = "STORY"
  url = "/story/"
  weight = 40

[[menu.main]]
  identifier = "blog"
  name = "BLOG"
  url = "/writings/"
  weight = 50

[[menu.main]]
  identifier = "contact"
  name = "CONTACT"
  url = "/#contact"
  weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
