baseURL = 'https://shunta-furukawa.info/'
languageCode = 'ja-JP'
title = 'SHUNTA FURUKAWA INFO'

[[menu.main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "story"
  name = "ストーリー"
  url = "/story"
  weight = 20

[[menu.main]]
  identifier = "writings"
  name = "投稿"
  url = "/writings"
  weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
