baseURL = 'https://shunta-furukawa.info/'
languageCode = 'ja-JP'
title = 'SHUNTA FURUKAWA INFO'

[[menu.main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "story"
  name = "ストーリー"
  url = "/story"
  weight = 20

# [[menu.main]]
#   identifier = "tags"
#   name = "タグ"
#   url = '/tags'
#   weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
